## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Monero Roads"
copyright = "2024"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "All Roads lead to Monero"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  youtube = "https://youtube.com/moneroroads"
  github = "https://github.com/MoneroRoads/"
  x = "https://x.com/MoneroRoads"
  email = "moneroroads@protonmail.com"
  instagram = "https://www.instagram.com/moneroroads/"
  telegram = "https://t.me/MoneroRoads"
  monero = "87hiexnDraV3TVD5jxmMYXSqg1oXNSiAd7GanZHoZwYBJwEHdR8MdsyF6s5AiKCdNW8QfuD4xVJjkC8osEY6TcAP91MZGA8?recipient_name=MoneroRoads"
  session = "05b165bfc466e3fb21c7218aaeb943d70f4304949e474e944d4ca136951bd18c2c"
  signal = "https://signal.me/#eu/PEbqey__IiV3set2I11emHlpRk56_EPxDkcKJcQYiTZhwTeooNBA-a-Y5eW5CykZ"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
