## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Monero Roads"
copyright = "2024"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "All Roads lead to Monero"
  logo = "images/banner.jpg"
  favicon = true

[Params.style]
fg = "#ff6600"
fg-bold = "#ff6600"

[Params.social]
  youtube = "https://www.youtube.com/@MoneroRoads"
  github = "https://github.com/MoneroRoads/"
  x = "https://x.com/MoneroRoads"
  email = "moneroroads@protonmail.com"
  instagram = "https://www.instagram.com/moneroroads/"
  vimeo = "https://vimeo.com/moneroroads"
  twitch = "https://www.twitch.tv/moneroroads"
  monero = "87hiexnDraV3TVD5jxmMYXSqg1oXNSiAd7GanZHoZwYBJwEHdR8MdsyF6s5AiKCdNW8QfuD4xVJjkC8osEY6TcAP91MZGA8?recipient_name=MoneroRoads"
  telegram = "https://t.me/MoneroRoads"
  session = "05b165bfc466e3fb21c7218aaeb943d70f4304949e474e944d4ca136951bd18c2c?username=MoneroRoads"
  simplex = "https://simplex.chat/contact/#/?v=2-7&smp=smp%3A%2F%2Fh--vW7ZSkXPeOUpfxlFGgauQmXNFOzGoizak7Ult7cw%3D%40smp15.simplex.im%2Fe5_AkAg9wVerx8ssrPq0ddpjvlz-SAr1%23%2F%3Fv%3D1-3%26dh%3DMCowBQYDK2VuAyEAQAx3_FFfIBHVWRw9RKgGGl-1Rh2CwPsIH8WiR_owaC8%253D%26srv%3Doauu4bgijybyhczbnxtlggo6hiubahmeutaqineuyy23aojpih3dajad.onion"
  nostr = "npub1m86vau8js7kqkt6fgxht536ecp224yvwv06dpdczdje3qckxthdqkd0520"
  signal = "https://signal.me/#eu/PEbqey__IiV3set2I11emHlpRk56_EPxDkcKJcQYiTZhwTeooNBA-a-Y5eW5CykZ"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
