## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Monero Roads"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "All Roads lead to Monero"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/MoneroRoads/"
  twitter = "https://x.com/MoneroRoads"
  email = "moneroroads@protonmail.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
